#include <stdio.h>

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
// The solution is 4613732



int main() {
        static const int MAX_FIB_VALUE = 4000000;

        int current, sum;
        int lastnums[2] = {1, 2};

        current = 0;
        sum = 2;

        while (current < MAX_FIB_VALUE) {
                if (current % 2 == 0) {
                        sum += current;
                }

                current = lastnums[0] + lastnums[1];
                lastnums[0] = lastnums[1];
                lastnums[1] = current;
        }

        printf("%i", sum);
}